{
 "title": "HMI Individual Project Visualization",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Population_dropdown",
    "query": "2022 Population, 2020 Population, 2015 Population, 2010 Population, 2000 Population, 1990 Population, 1980 Population, 1970 Population"
   },
   {
    "name": "selected_country",
    "query": "SELECT `Country/Territory` FROM world_population ORDER BY `Country/Territory` ASC;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Population",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    SUM(`${Population_dropdown}`)\r\nFROM \r\n    world_population"
    }
   ]
  },
  {
   "title": "Growth Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n`Country/Territory`,\r\n`Growth Rate`\r\nFROM hmi.world_population\r\nWHERE\r\n    `Country/Territory` = \"${selected_country:raw}\";"
    }
   ]
  },
  {
   "title": "Total Population by Continent",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "hmi",
     "rawSql": "SELECT Continent, SUM(`${Population_dropdown}`) FROM hmi.world_population GROUP BY Continent ORDER BY SUM(`${Population_dropdown}`) ASC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Countries with the lowest population densities",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    `Country/Territory`, \r\n    `Density (per km²)`\r\nFROM \r\n    world_population\r\nORDER BY \r\n    `Density (per km²)` ASC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Most Populated Country",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    `Rank`,\r\n    `Country/Territory`, \r\n    `${Population_dropdown}`\r\nFROM \r\n    world_population\r\nORDER BY \r\n    `Rank` ASC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Countries with the highest population densities",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    `Country/Territory`, \r\n    `Density (per km²)`\r\nFROM \r\n    world_population\r\nORDER BY \r\n    `Density (per km²)` DESC\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}